### ISSUE TITLE
180719 D조 가드닝

### ISSUE THREAD

**Issue by wo1ever** [dataitgirls2/10minutes2pandas#49]
D조 가드닝 내역 입니다!

**Comment by LunarKim** [comment]
- [ ]

**Comment by SaeromB** [comment]
-[] 예시

**Comment by Yoonkimove** [comment]
- [ ] 72-74

**Comment by Yoonkimove** [comment]
Join 앞 df.iloc[:,1:3]

**Comment by wo1ever** [comment]
Histogramming - 경어체 수정

**Comment by corazzon** [comment]
@wo1ever @Yoonkimove @LunarKim @SaeromB 고생 많으셨습니다. 개선한 부분도 남겨주셔서 좋네요! 다음조(@YoungestSalon @DayoungHong @HeeYoungK @Dalbongjooin)도 화이팅입니다!

**Comment by YoungestSalon** [comment]
D조 여러분 수고하셨습니다. :smiley: 
G조 가드닝도 Issue 개설했기 때문에 D조 가드닝 Issue는 Close 처리하겠습니다. :+1:
