### ISSUE TITLE
180722 G조 가드닝

### ISSUE THREAD

**Issue by YoungestSalon** [dataitgirls2/10minutes2pandas#50]
10 Minutes to Pandas 공동번역 G조 가드닝 내역입니다. :smile:

**Comment by YoungestSalon** [comment]
- [ ] 경어체 수정
- [ ] 용어 통일 (Operation = 연산, Function = 함수)
- [ ] 일부 번역 수정 / 주석 추가 (원문 문장이 너무 길거나, 의미가 불확실한 경우)
- [ ] Python / Pandas 함수 부분 'In []' 번호  정리
- [ ] 참고 문헌 추가 : Pandas 개발자 Pycon 영상(Youtube) 등

**Comment by corazzon** [comment]
@wo1ever @gabining @ddongule @chaewon0917  오늘 가드닝은 월요일 조가 해주실거에요.
이 이슈를 닫고 G조 처럼 새로운 이슈를 만들어서 진행해 주세요.

@DayoungHong @Dalbongjooin @YoungestSalon @HeeYoungK  고생 많으셨습니다 👍

**Comment by YoungestSalon** [comment]
@wo1ever @gabining @ddongule @chaewon0917님, 가드닝 한번 더 수정해서 오늘 점심시간 내로 다시 올릴 예정이에요. 수정하고 나면 다시 코멘트 남기겠습니드.

번거로우시겠지만 점심시간 이후에 가드닝 진행 부탁드립니다. 감사합니다 :)
