### ISSUE TITLE
180723_A조 가드닝

### ISSUE THREAD

**Issue by wo1ever** [dataitgirls2/10minutes2pandas#51]
- [x] 코드 셀 배치가 제대로 되어 있는 지 확인

- [x] 텍스트 셀 배치가 제대로 되어 있는 지 확인

- [x] 경어체 확인

- [x] 맞춤법 확인

- [x] 링크가 제대로 되어 있는 지 확인

- [x] 용어 수정

**Comment by YoungestSalon** [comment]
A조 여러분(@chaewon0917 @ddongule @wo1ever @gabining) 수고하셨습니다!
H조 이번 주말 가드닝 이슈 새로 생성하겠습니다 😄
