### ISSUE TITLE
BUG: broken link to http://dataitgirls2.pagedemo.co/ 

### ISSUE THREAD

**Issue by swyoon** [dataitgirls2/10minutes2pandas#63]
[10minutes2pandas](https://dataitgirls2.github.io/10minutes2pandas/) 를 잘 읽고 있던 도중 이슈를 발견하여 보고합니다.

`http://dataitgirls2.pagedemo.co/` 홈페이지로 이어지는 링크가 전체 문서에 여러 개 있는데, 이 홈페이지가 현재 작동이 되지 않습니다. `Looks like you're lost`라는 메세지가 보입니다. 이 홈페이지의 문제인 것 같습니다.

![image](https://user-images.githubusercontent.com/10072033/44128168-6d594b1e-a07c-11e8-99f1-293f343ea277.png)

**Comment by HeeYoungK** [comment]
감사합니다!
데잇걸즈2 홈페이지 링크 변경 완료했습니다.
