### ISSUE TITLE
BUG: two scroll bars appear in code blocks

### ISSUE THREAD

**Issue by swyoon** [dataitgirls2/10minutes2pandas#64]
10 minutes to pandas의 화면 상 코드블록이 전부 스크롤바를 두 겹으로 가지고 있는 것으로 나타납니다. Chrome과 Firefox에서 둘 다 같은 현상이 나타납니다.

![image](https://user-images.githubusercontent.com/10072033/44128257-fb7c6e4e-a07c-11e8-8c6d-2895f4746356.png)

예상되는 원인은 main.css의 div tag에 붙어있는 overflow-x: scroll; 인 것 같습니다. 개발자도구에서 이 태그를 없애면 스크롤바가 없어집니다.

before:

![image](https://user-images.githubusercontent.com/10072033/44128351-83ef0192-a07d-11e8-86db-092b57981fdd.png)

after:

![image](https://user-images.githubusercontent.com/10072033/44128423-dd9c4a2e-a07d-11e8-94eb-fe178803025d.png)

**Comment by aeranghang** [comment]
고맙습니다 :)

**Comment by swyoon** [comment]
판다스 스프린트에 왔다가 그만... ;) 수고하세요!
