### ISSUE TITLE
H조: `git checkout 8_141_to_Gotchas`

### ISSUE THREAD

**Issue by corazzon** [dataitgirls2/10minutes2pandas#8]
10minutes2pandas 번역 실습 및 과제
README.md 파일을 참고하여 번역할 부분을 나누고 해당 브랜치로 이동해서 작업합니다.

- [x] 각자 번역할 부분을 팀원들과 나눈다. 
- [x] 10minutes2pandas 저장소를 내 저장소로 포크해 온다.
- [x] 로컬 경로로 클론 받아 온다.
- [ ] `git checkout 우리팀브랜치` 로 브랜치를 변경한다.
- [ ] `git pull --rebase origin master` 로 마스터 브랜치의 소스를 현재 브랜치에 반영해 준다.
- [ ] 아나콘다에서 해당 노트북(index.ipynb)을 불러온다.
- [ ] 아나콘다에서 index.ipynb 에 자신이 번역할 부분을 번역한다.
- [ ] 소스트리를 사용해서 클론받아 온 저장소를 불러온다.
- [ ] 소스트리를 통해 변경내용을 add, commit, push 한다. (이 때 마스터브랜치가 아닌 자신의 조 브랜치로 push한다.)
- [ ] 터미널을 통해 push 한다면 git push origin 우리팀브랜치 로 push 한다.
- [ ] 컨플릭이 발생하면 해결하고 모든 팀원의 작업이 끝나면 마스터 브랜치로 pull request를 생성한다.

**Comment by miningful** [comment]
@SaeromB - CSV
@chaewon0917 - HDF5
@miningful - Excel
@jyeeee95 - Gotchas
